# conda environments:
#
local                 *  /users/PAA0023/mason1099/.conda/envs/local
base                     /usr/local/python/3.6-conda5.2

/users/PAA0023/mason1099/.conda/envs/local/bin/python
2022-04-17 15:21:40.192732: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-04-17 15:21:57.987536: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-04-17 15:21:58.002163: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2022-04-17 15:21:58.033268: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-04-17 15:21:58.033362: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: o0714.ten.osc.edu
2022-04-17 15:21:58.033395: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: o0714.ten.osc.edu
2022-04-17 15:21:58.033555: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 510.47.3
2022-04-17 15:21:58.033653: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 510.47.3
2022-04-17 15:21:58.033681: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 510.47.3
2022-04-17 15:22:31.341732: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
gpus:  []
config:
 {'model_type': 'vae', 'data_type': 'cube_slices_128', 'nn_type': 'cnn', 'img_size': 128, 'img_channels': 1, 'batch_size': 128, 'epochs': 40, 'data_dir': '../data/', 'model_dir': '../save_model_vae/tf/', 'recon_loss_type': 'bce', 'is_bn': False, 'is_load_pretrain': False, 'z_dim': 2, 'select_seed': 2036, 'img_dir': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036/', 'fig_loss': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//loss.png', 'fig_recons': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//recon_example.png', 'fig_zmeans': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//param_predictions.png', 'fig_2d_variation': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//fig_2d_variation.png', 'cls_report': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//cls_report.txt', 'fig_reg_true_prediction': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//reg_true_prediction', 'load_model_weights': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//vae_cube_slices_128_cnn.h5', 'load_enc_weights': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//vae_enc_cube_slices_128_cnn.h5', 'load_dec_weights': '../save_model_vae/tf//cube_slices_128/vae_img_cube_slices_128_cnn_bce_bnFalse_seed2036//vae_dec_cube_slices_128_cnn.h5'}
(5000, 16385)
x.shape: (5000, 16384), y.shape: (5000, 1)
number of class: 5
min and max of x: 0.00, 1.00
x_train.shape: (4000, 128, 128, 1), x_test.shape: (1000, 128, 128, 1), y_train.shape: (4000, 1), y_test.shape: (1000, 1)

(128, 128, 1)
Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
encoder_input (InputLayer)      [(None, 128, 128, 1) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 63, 63, 64)   1088        encoder_input[0][0]              
__________________________________________________________________________________________________
dropout (Dropout)               (None, 63, 63, 64)   0           conv2d[0][0]                     
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 30, 30, 128)  131200      dropout[0][0]                    
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 30, 30, 128)  0           conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 15, 15, 512)  262656      dropout_1[0][0]                  
__________________________________________________________________________________________________
reshape (Reshape)               (None, 115200)       0           conv2d_2[0][0]                   
__________________________________________________________________________________________________
z_mean (Dense)                  (None, 2)            230402      reshape[0][0]                    
__________________________________________________________________________________________________
z_std (Dense)                   (None, 2)            230402      reshape[0][0]                    
__________________________________________________________________________________________________
z (Lambda)                      (None, 2)            0           z_mean[0][0]                     
                                                                 z_std[0][0]                      
==================================================================================================
Total params: 855,748
Trainable params: 855,748
Non-trainable params: 0
__________________________________________________________________________________________________
Model: "decoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
z_sampling (InputLayer)      [(None, 2)]               0         
_________________________________________________________________
dense (Dense)                (None, 2048)              6144      
_________________________________________________________________
reshape_1 (Reshape)          (None, 2, 2, 512)         0         
_________________________________________________________________
conv2d_transpose (Conv2DTran (None, 6, 6, 128)         1048704   
_________________________________________________________________
dropout_2 (Dropout)          (None, 6, 6, 128)         0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 14, 14, 64)        131136    
_________________________________________________________________
dropout_3 (Dropout)          (None, 14, 14, 64)        0         
_________________________________________________________________
conv2d_transpose_2 (Conv2DTr (None, 28, 28, 1)         257       
=================================================================
Total params: 1,186,241
Trainable params: 1,186,241
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1853, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 128 and 28 for '{{node tf.keras.metrics.binary_crossentropy/mul/mul}} = Mul[T=DT_FLOAT](Placeholder, tf.keras.metrics.binary_crossentropy/Log)' with input shapes: [?,128,128,1], [?,28,28,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1175, in binary_op_wrapper
    out = r_op(x)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1195, in r_binary_op_wrapper
    return func(x, y, name=name)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1496, in _mul_dispatch
    return multiply(x, y, name=name)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 518, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6078, in mul
    "Mul", x=x, y=y, name=name)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 592, in _create_op_internal
    compute_device)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2016, in __init__
    control_input_ops, op_def)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1856, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 128 and 28 for '{{node tf.keras.metrics.binary_crossentropy/mul/mul}} = Mul[T=DT_FLOAT](Placeholder, tf.keras.metrics.binary_crossentropy/Log)' with input shapes: [?,128,128,1], [?,28,28,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tf_vae.py", line 96, in <module>
    model, encoder, decoder = vae.build_cnn_vae()
  File "/users/PAA0023/mason1099/VAE_shape_variation/src/tf_vae.py", line 112, in build_cnn_vae
    recon_loss, kl_loss, vae_loss = self.vae_loss_func(input1, output1, z_mean, z_std)
  File "/users/PAA0023/mason1099/VAE_shape_variation/src/tf_vae.py", line 154, in vae_loss_func
    recon_loss = binary_crossentropy(y_true, y_pred)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 205, in wrapper
    result = dispatch(wrapper, args, kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 122, in dispatch
    result = dispatcher.handle(op, args, kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 1450, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 1327, in _call_wrapper
    return self._call_wrapper(*args, **kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 1359, in _call_wrapper
    result = self.function(*args, **kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/losses.py", line 1608, in binary_crossentropy
    K.binary_crossentropy(y_true, y_pred, from_logits=from_logits), axis=-1)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 4994, in binary_crossentropy
    bce = target * math_ops.log(output + epsilon())
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1180, in binary_op_wrapper
    raise e
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1164, in binary_op_wrapper
    return func(x, y, name=name)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1496, in _mul_dispatch
    return multiply(x, y, name=name)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 518, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6078, in mul
    "Mul", x=x, y=y, name=name)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 592, in _create_op_internal
    compute_device)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2016, in __init__
    control_input_ops, op_def)
  File "/users/PAA0023/mason1099/.conda/envs/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1856, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 128 and 28 for '{{node tf.keras.metrics.binary_crossentropy/mul}} = Mul[T=DT_FLOAT](Placeholder, tf.keras.metrics.binary_crossentropy/Log)' with input shapes: [?,128,128,1], [?,28,28,1].
